### ISSUE TITLE
Expose License Key at rtmedia.io

### ISSUE THREAD

**Issue by MiteshShah** [rtCamp/rtMedia#2036]
```
104.198.7.79 BYPASS [10/Jan/2024:08:43:28 +0000] rtmedia.io "GET /?edd_action=activate_license&license=XXXXXXXXXXXXXXXXX&item_name=rtMedia%20Docs%20and%20Other%20files&url=https://www.inblf.com HTTP/1.1" 200 134 "-" "WordPress/6.4.2; https://example.com"0.254 0.255
104.236.212.59 BYPASS [10/Jan/2024:08:44:12 +0000] rtmedia.io "GET /rt-eddsl-api?rt-eddsl-license-key=XXXXXXXXXXXXXXX HTTP/1.1" 200 330 "-" "GuzzleHttp/7"0.464 0.464
```

Sending sensitive information (API or License key) in query parameters is generally not recommended for security reasons. URLs are often logged in various places, such as browser history, server logs, and can be exposed in shared links, posing a security risk.

@gagan0123

**Comment by Utsav-Ladani** [comment]
Hi @MiteshShah 

This issue is resolved with [this](https://github.com/rtCamp/rtMedia/pull/2037) PR. We will add it in the next release.

Thanks

CC: @gagan0123

**Comment by MiteshShah** [comment]
@Utsav-Ladani I can see PR is merged already.
Do we close this issue if we released a fix already ?

**Comment by Utsav-Ladani** [comment]
@MiteshShah, the fix has been added in the pre-release branch but has yet to be released. 

It is added in milestone `v4.6.18`. So, we have to keep this PR open until milestone `v4.6.18` is released. Will let you know once the plugin is released.

**Comment by pavanpatil1** [comment]
It is fixed, Hence closing this issue

**Comment by MiteshShah** [comment]
@pavanpatil1 I can still see the license keys on logs still as on 4th Nov 2024.
cc: @radhe

**Comment by krishana7911** [comment]
Hi @MiteshShah can you please share recent logs for reference regarding the issue.

**Comment by MiteshShah** [comment]
@krishana7911 - https://rtcamp.slack.com/archives/CGRL6NAQL/p1730870282131599

**Comment by nitun** [comment]
@krishana7911 please look into this. Its important task.

**Comment by krishana7911** [comment]
Hii team, 
The issue has been resolved, and we won't see the license key issue exposed from users with updated versions of the plugins. 
- we have added the fix for all license related request which included `activation` `deactivation` and `check license`
- The fix has been added to the individual addon plugins as well as to the pro version with both variants - premium and agency plan. 

Reference links: 
- https://rtcamp.slack.com/archives/C036KNFNY/p1730719651015999 
- https://rtcamp.slack.com/archives/C036KNFNY/p1734683011908219
-  https://github.com/rtCamp/rtMedia-Pro/pull/1463/
